sudo: required
dist: trusty
language: java
jdk:
  - openjdk8 

cache:
  directories:
  - $HOME/.m2
  - grakn-dashboard/node_modules
  - grakn-engine/npm

env:
  # Split tests into grakn-test and everything else
  - TESTS=**/*Test* MODULE=grakn-test/test-integration
  - TESTS=**/*IT*   MODULE=grakn-test/test-integration
  - TESTS=**/*Test* MODULE=!grakn-test/test-integration
  - TESTS=**/*IT*   MODULE=!grakn-test/test-integration

notifications:
  slack: grakn:RbxoPzX267spGT4cgmoGLMpT
  email: false
  
install: mvn install -T 2.5C -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
    - mvn test --projects "$MODULE" -Dtest=$TESTS -DfailIfNoTests=false jacoco:report
    - bash <(curl -s https://codecov.io/bash)
before_install:
  - npm config set registry http://registry.npmjs.org/
