server:
  type: default
  maxThreads: 1024

server:
  requestLog:
    appenders:
      - type: console


server:
  adminMinThreads: 1
  adminMaxThreads: 64
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 4567
  adminConnectors:
    - type: http
      port: 4568